// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu4SgQZG865ScyaO-zuVGjOjuoh6AU_8w',
    appId: '1:1065169581449:web:97611e5279b3d903849d58',
    messagingSenderId: '1065169581449',
    projectId: 'medical-store-app-6a189',
    authDomain: 'medical-store-app-6a189.firebaseapp.com',
    storageBucket: 'medical-store-app-6a189.firebasestorage.app',
    measurementId: 'G-G9M37Q888J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrIIKgCJUoOQV-l3F29AxcejwRu5Dw7Ds',
    appId: '1:1065169581449:android:ae346b521b1c91db849d58',
    messagingSenderId: '1065169581449',
    projectId: 'medical-store-app-6a189',
    storageBucket: 'medical-store-app-6a189.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDc4ONauJ4OXkxk4yexjrm7U5qKBcxBDM',
    appId: '1:1065169581449:ios:7ab496dc9da85fb8849d58',
    messagingSenderId: '1065169581449',
    projectId: 'medical-store-app-6a189',
    storageBucket: 'medical-store-app-6a189.firebasestorage.app',
    iosBundleId: 'com.example.medicalStoreApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDc4ONauJ4OXkxk4yexjrm7U5qKBcxBDM',
    appId: '1:1065169581449:ios:7ab496dc9da85fb8849d58',
    messagingSenderId: '1065169581449',
    projectId: 'medical-store-app-6a189',
    storageBucket: 'medical-store-app-6a189.firebasestorage.app',
    iosBundleId: 'com.example.medicalStoreApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCu4SgQZG865ScyaO-zuVGjOjuoh6AU_8w',
    appId: '1:1065169581449:web:698d304690fe583f849d58',
    messagingSenderId: '1065169581449',
    projectId: 'medical-store-app-6a189',
    authDomain: 'medical-store-app-6a189.firebaseapp.com',
    storageBucket: 'medical-store-app-6a189.firebasestorage.app',
    measurementId: 'G-MX4Q1GH8PE',
  );
}
