// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGizHaOdXtQ_ANL9_8QwPXhj84bTbhssY',
    appId: '1:1095879858346:web:7ab4af8545f098a41f58d3',
    messagingSenderId: '1095879858346',
    projectId: 'medical-store-app-13a49',
    authDomain: 'medical-store-app-13a49.firebaseapp.com',
    storageBucket: 'medical-store-app-13a49.firebasestorage.app',
    measurementId: 'G-41GZPB77BM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH9hdtqVxOkJGrVARLS6dFrRJ4pOiFqLo',
    appId: '1:1095879858346:android:6d5cd47242c38bf31f58d3',
    messagingSenderId: '1095879858346',
    projectId: 'medical-store-app-13a49',
    storageBucket: 'medical-store-app-13a49.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN780lsMnkkk8CKwpqBSP8ckAR9p7X5Ek',
    appId: '1:1095879858346:ios:00f7125aed7495521f58d3',
    messagingSenderId: '1095879858346',
    projectId: 'medical-store-app-13a49',
    storageBucket: 'medical-store-app-13a49.firebasestorage.app',
    iosBundleId: 'com.example.medicalStoreApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBN780lsMnkkk8CKwpqBSP8ckAR9p7X5Ek',
    appId: '1:1095879858346:ios:00f7125aed7495521f58d3',
    messagingSenderId: '1095879858346',
    projectId: 'medical-store-app-13a49',
    storageBucket: 'medical-store-app-13a49.firebasestorage.app',
    iosBundleId: 'com.example.medicalStoreApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGizHaOdXtQ_ANL9_8QwPXhj84bTbhssY',
    appId: '1:1095879858346:web:fe58192e37ba93391f58d3',
    messagingSenderId: '1095879858346',
    projectId: 'medical-store-app-13a49',
    authDomain: 'medical-store-app-13a49.firebaseapp.com',
    storageBucket: 'medical-store-app-13a49.firebasestorage.app',
    measurementId: 'G-19PQRGBG7B',
  );
}
